const CTechs = {
    Astro: "astro",
    AutoAnimate: "AutoAnimate",
    axios: "axios",
    cypress: "Crypess",
    Firebase: "firebase",
    i18next: 'i18next',
    JavaScript: "javaScript",
    joyUI: "JoyUI",
    jsonBin: 'jsonBin',
    million: 'million',
    Nextjs: "next.js",
    React: "react",
    ReactHookForm: "ReactHookForm",
    ReactRouterDom: "react router dom",
    Sooner: "sooner",
    swr: 'swr',
    Typescript: "typeScript",
    Zod: "zod",
}
export { CTechs }
